sylius_grid:
    grids:
        app_admin_newsletter:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Newsletter
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                content:
                    type: string
                    label: newsletter_test.ui.content
                status:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [ code, translation.name, content ]
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
